<template>
  <div class=terms-sale-bg><div class="Section0"><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_w69w1nxg4auu"></a><img width="98" height="98" src="@/assets/images/onecare_logo.png"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">TERMS OF SALE</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">These Terms of Sale (“Terms”) apply to all orders placed by you through OneCare’s mobile app, website, or via phone with OneCare’s customer support (collectively the “OneCare Store”). By placing any order through the OneCare Store, you are agreeing to be bound by these Terms. You represent and warrant that you have the legal capacity to agree to these Terms. If you are under the age of thirteen, or any higher minimum age in your jurisdiction, you represent and warrant that you have obtained parental or guardian consent to enter into these Terms. If your order includes paid services, our Terms for Paid Services are hereby incorporated into these Terms. These Terms are between you and OneCare, Inc., and, if applicable, the reseller appointed by OneCare, Inc. as identified in the OneCare Store or in your order confirmation. In these Terms, “OneCare” and “we” mean OneCare, Inc. and/or its affiliates and, if applicable, any such reseller.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_2f7nahg04569"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">RETURN POLICY</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">If you are unsatisfied with your purchase of a OneCare-branded device and/or accessory from the OneCare Store for any reason, you are entitled to a full refund if you meet the conditions set forth below. This return right does not apply to the purchase or renewal of any Paid Services, as defined in and governed by our Terms for Paid Services. Shipping and handling charges, gift wrap fees, and taxes paid (such as state, customs, or VAT) are not refundable. To qualify for a refund, you must meet all the following conditions:</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-top:4.0000pt;margin-left:36.0000pt;text-indent:-18.0000pt;
background:rgb(255,255,255);mso-list:l0 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:'Playfair Display Regular';color:rgb(87,101,105);font-size:15.0000pt;"><span style="mso-list:Ignore;">●<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">request a return authorization within 30 days of your shipment date; </span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0000pt;text-indent:-18.0000pt;background:rgb(255,255,255);
mso-list:l0 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:'Playfair Display Regular';color:rgb(87,101,105);font-size:15.0000pt;"><span style="mso-list:Ignore;">●<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">return the device and/or accessory, including all parts included in the original packaging, in good physical condition; and</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-bottom:4.0000pt;margin-left:36.0000pt;text-indent:-18.0000pt;
background:rgb(255,255,255);mso-list:l0 level1 lfo1;"><!--[if !supportLists]--><span style="font-family:'Playfair Display Regular';color:rgb(87,101,105);font-size:15.0000pt;"><span style="mso-list:Ignore;">●<span>&nbsp;</span></span></span><!--[endif]--><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">include the return authorization number with your return.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">If your return fails to meet any of the above conditions, we may, in our discretion, refuse to accept it or charge you a restocking fee of up to 15% of the original price.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_4trac21h3p9x"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">LIMITED PRODUCT WARRANTY</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Your use of OneCare-branded devices and accessories is subject to OneCare’s applicable </span><span><a href="https://www.fitbit.com/us/legal/returns-and-warranty"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,42,58);
font-size:14.0000pt;">Limited Product Warranty.</span></a></span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;OneCare’s Limited Product Warranty does not apply to third-party products or accessories that may be sold on the OneCare Store. For warranty issues related to those products, please contact that manufacturer.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_p9m8kjtdxnp7"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">NOT FOR RESALE</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">The OneCare Store sells and ships products to end-user customers only, and we reserve the right to refuse or cancel your order if we suspect you are purchasing products for resale.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_rxmw9da51yq7"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">PRICING</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Prices may not include shipping and handling charges or applicable taxes, which, if applicable, will be communicated to you before you place your order. We reserve the right to change the prices for any products or services in the OneCare Store at any time without notice.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_apoh4g5mopxk"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">ORDERING, SHIPPING AND DELIVERY</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">We may refuse or cancel any order or limit any order quantity in our sole discretion, even after receiving your order. We may also require additional qualifying information prior to accepting or processing your order. While it is our practice to confirm orders by email, your receipt of an email confirmation does not constitute our acceptance of your order or our confirmation of an offer to sell a product or service.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">If you wish to make a transaction through the OneCare Store, you may be asked to supply certain relevant information, such as your payment and shipping information. YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT TO USE ANY PAYMENT METHOD THAT YOU CHOOSE TO USE TO COMPLETE ANY SUCH TRANSACTION. By submitting such information, you grant to us the right to provide such information to third parties for purposes of facilitating transactions. Verification of information may be required prior to the acknowledgment or completion of any transaction.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">The actual delivery of your order can be impacted by many events beyond our control, and you agree we are not liable for late deliveries. Title to the products will pass to you upon delivery of the products to the carrier; however, risk of loss of, or damage to, the products will pass to you upon delivery of the products to you.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">In certain regions, although we are the operator of the OneCare Store, the products and services may be sold to you by our appointed reseller, as the seller of record, pursuant to contractual arrangements between us and the reseller. As described above, this means you have a contract with that appointed reseller for the supply of those products and services. In such case, the point of purchase or your order confirmation will include the appropriate contact information for any issues relating to your order. OneCare, Inc. and its affiliates are express third-party beneficiaries of these Terms in cases where these Terms are between you and the appointed reseller.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_v41054743rlv"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">PRODUCT AND SERVICE AVAILABILITY</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">We reserve the right to add or remove products and services from the OneCare Store at any time for any reason. We also reserve the right to change quantities available for purchase at any time, even after you place an order.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">We make no representations as to the completeness, accuracy, reliability, validity or timeliness of any listings, descriptions or images (including, without limitation, any features and specifications such as weights and sizes) for any products or services available through the OneCare Store. Such information and the availability of any product or service (including, without limitation, the validity of any coupon or discount) are subject to change at any time without notice. It is your responsibility to understand and comply with all applicable local, state, federal and foreign laws (including minimum age requirements) regarding the purchase, possession and use of any product or service.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_kunq602v8wfo"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">COMPATIBILITY</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">You are solely responsible for determining the compatibility of the products and services with any required equipment (e.g., ensuring that you are using a compatible mobile device). You agree that lack of compatibility does not constitute a defect giving rise to a claim under our Limited Product Warranty.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_br5ygbfmewn2"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">SOFTWARE LICENSE</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">To the extent the products ordered by you contain, consist of, or make available OneCare software in any form, such software is licensed to you and not sold, in accordance with our Terms of Service. </span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,42,58);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_lw19s4lvoa1z"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">LIMITATIONS ON LIABILITY</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">EXCEPT TO THE EXTENT PROHIBITED BY APPLICABLE LAW, NEITHER ONECARE, ITS SUPPLIERS, DISTRIBUTORS, OR LICENSORS, NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING ONECARE PRODUCTS AND SERVICES WILL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE, OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE ONECARE PRODUCTS OR SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ONECARE OR ITS SUPPLIER, DISTRIBUTOR, RESELLER, OR LICENSOR, OR OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING ONECARE PRODUCTS AND SERVICES HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">IN NO EVENT WILL THE AGGREGATE, TOTAL LIABILITY OF ONECARE, OR ITS SUPPLIER, DISTRIBUTOR, RESELLER, OR LICENSOR, OR OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING ONECARE PRODUCTS AND SERVICES, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE ONECARE PRODUCTS OR SERVICE EXCEED THE AMOUNTS YOU HAVE PAID FOR YOUR APPLICABLE PURCHASE.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN ONECARE AND YOU.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_1o1q41gzznt2"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">DISPUTE RESOLUTION</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;PLEASE READ THE FOLLOWING SECTION CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE CERTAIN DISPUTES AND CLAIMS WITH US AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM US.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">You agree that any dispute between you and OneCare arising out of or relating to your order via the OneCare Store (collectively, “Disputes”) will be governed by the arbitration procedure outlined below.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">GOVERNING LAW</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Except as otherwise required by applicable law, the Terms and the resolution of any Disputes shall be governed by and construed in accordance with the laws of the State of Indiana without regard to its conflict of laws principles.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">INFORMAL DISPUTE RESOLUTION</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">We want to address your concerns without needing a formal legal case. Before filing a claim against OneCare, you agree to try to resolve the Dispute informally by contacting </span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,42,58);
font-size:14.0000pt;">support@onecaresaves.com</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">. We'll try to resolve the Dispute informally by contacting you through email. If a dispute is not resolved within 15 days after submission, you or OneCare may bring a formal proceeding.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">WE BOTH AGREE TO ARBITRATE</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">You and OneCare agree to resolve any Disputes through final and binding arbitration, except as set forth under Exceptions to Agreement to Arbitrate below.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">OPT-OUT OF AGREEMENT TO ARBITRATE</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">You can decline this agreement to arbitrate by contacting </span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,42,58);
font-size:14.0000pt;">optout@onecaresaves.com</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;within 30 days of first accepting these Terms and stating that you (include your first and last name) decline this arbitration agreement.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">ARBITRATION PROCEDURES</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">The American Arbitration Association (AAA) will administer the arbitration under its Consumer Arbitration Rules. The arbitration will be held in the United States county where you live or work, San Francisco, California, or any other location we agree to.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">ARBITRATION FEES</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">The AAA rules will govern payment of all arbitration fees. OneCare will pay all arbitration fees for claims less than $75,000. OneCare will not seek its attorneys' fees and costs in arbitration unless the arbitrator determines that your claim is frivolous.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">EXCEPTIONS TO AGREEMENT TO ARBITRATE</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Either you or OneCare may assert claims, if they qualify, in small claims court in Batesville, Indiana or any United States county where you live or work. Either party may bring a lawsuit solely for injunctive relief to stop unauthorized use or abuse of the OneCare products or services, or infringement of intellectual property rights (for example, trademark, trade secret, copyright or patent rights) without first engaging in arbitration or the informal dispute-resolution process described above.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">NO CLASS ACTIONS</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">You may only resolve Disputes with OneCare on an individual basis, and may not bring a claim as a plaintiff or a class member in a class, consolidated, or representative action. Class arbitrations, class actions, private attorney general actions, and consolidation with other arbitrations are not allowed under our agreement.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">JUDICIAL FORUM FOR DISPUTES</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Except as otherwise required by applicable law, in the event that the agreement to arbitrate is found not to apply to you or your claim, you and OneCare agree that any judicial proceeding (other than small claims actions) will be brought in the federal or state courts of Ripley County, Indiana. Both you and OneCare consent to venue and personal jurisdiction there. We both agree to waive our right to a jury trial.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">LIMITATION ON CLAIMS</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to your order from the OneCare Store must be filed within one (1) year after such claim or cause of action arose, or else that claim or cause of action will be barred forever.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_3ephjnebafzb"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">GENERAL PROVISIONS</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Except as otherwise stated herein, these Terms constitute the entire and exclusive understanding and agreement between us regarding any orders you make on the OneCare Store, and these Terms supersede and replace any and all prior oral or written understandings or agreements between us relating thereto.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">You may not assign, delegate, or transfer these Terms, by operation of law or otherwise, without OneCare’s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and void. OneCare may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors, and permitted assigns.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Any notices or other communications provided by OneCare under these Terms, including those regarding modifications to these Terms, will be given: (i) via email to any address you have provided to OneCare; or (ii) by posting to the OneCare Store. For notices made by email, the date on which the message is sent will be deemed the date on which such notice is transmitted.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">OneCare’s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of OneCare. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">You will not export or re-export, directly or indirectly, the products or services, or any technical information related thereto, to any destination or person prohibited or restricted by applicable law, including, without limitation, U.S. export control laws and regulations.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><h3 style="margin-top:0.0000pt;margin-bottom:0.0000pt;mso-pagination:none;
line-height:265%;background:rgb(255,255,255);"><a name="_szawnmooz8ne"></a><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;">ADDITIONAL TERMS MAY APPLY</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(0,176,185);
font-size:14.0000pt;"><o:p></o:p></span></h3><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;">&nbsp;</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(87,101,105);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="background:rgb(255,255,255);"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;">Additional terms may apply to certain products or services. In the event that there is a conflict between these Terms and any additional terms, the additional terms will control.</span><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';color:rgb(16,36,41);
font-size:14.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:'yes';font-family:'Playfair Display Regular';font-size:14.0000pt;"><o:p>&nbsp;</o:p></span></p></div></div>
</template>

<script>
  export default {
    name: "termsSale",
    props: {},
    data() {
      return {};
    },
    created() {
    },
    mounted() {
    },
    methods: {}
  };
</script>

<style lang="scss" scoped>
  @import '@/style/mixin.scss';
  .terms-sale-bg {
    @include table-bg;
    line-height: 2em;
    text-align: left;
    padding:30px 50px;
    main {

    }
  }
</style>